name: Python Linting

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run pylint
        uses: github/super-linter@v4
        env:
          LINTER_RULES_PATH: .pylintrc  # Optional, specify if you have a custom pylintrc file
