name: Lint Python Code

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black flake8

      - name: Run pylint
        run: |
          pylint ../my_module.py  # Replace with the path to your module or directory

      - name: Run black (code formatter)
        run: |
          black --check ../my_module.py  # Replace with the path to your module or directory

      - name: Run flake8
        run: |
          flake8 ../my_module.py  # Replace with the path to your module or directory
